apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
  labels:
    app: metadata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
        - name: metadata
          image: kingshukbansal/rapidfort/metadata
          ports:
           - containerPort: 8080
          envFrom:
            - configMapRef:
                name: metadata-configmap
            - secretRef:
                name: metadata-secret


