name: Deploy Backend Microservices

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:  # Optionally trigger on PR creation
    branches:
      - master

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    # Step 1: Log in to Docker Hub (if you plan to push Docker images)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 2: Build and Push Docker Images for Backend Microservices (Optional)
    - name: Build and Push Backend Images
      run: |
        cd word-to-pdf-converter-backend
        for service in gateway docx-to-pdf-converter notification metadata download; do
          echo "Building and pushing $service..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rapidfort-$service:latest $service
          docker push ${{ secrets.DOCKER_USERNAME }}/rapidfort-$service:latest
        done

