name: Deploy Backend Microservices

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Repository
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Add SSH Key for EC2 Access
      run: |
        # Write the SSH key directly to /tmp/id_rsa.pem from GitHub Secrets
        echo "${{ secrets.SSH_KEY }}" > /tmp/id_rsa.pem

        # Set the correct permissions for the SSH key
        chmod 600 /tmp/id_rsa.pem

        # Optional: verify the contents of the key (for debugging)
        cat /tmp/id_rsa.pem




    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # # Step 3: Build and Push Docker Images for Backend Microservices
    # - name: Build and Push Backend Images
    #   run: |
    #     cd word-to-pdf-converter-backend
    #     for service in gateway docx-to-pdf-converter notification metadata download; do
    #       echo "Building and pushing $service..."
    #       docker build -t ${{ secrets.DOCKER_USERNAME }}/rapidfort-$service:latest $service
    #       docker push ${{ secrets.DOCKER_USERNAME }}/rapidfort-$service:latest
    #     done

    # # Step 4: Add SSH Key for EC2 Access (this should be before the deploy step)
    # - name: Add SSH Key
    #   run: |
    #     echo "${{ secrets.SSH_KEY }}" | base64 --decode > /tmp/id_rsa
    #     chmod 600 /tmp/id_rsa


    - name: SSH to EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Set the repository URL and directory name
          REPO_URL="https://github.com/KingshukBansal/RapidFort-Assignment.git"  # Replace with your actual repository URL
          REPO_DIR="word-to-pdf-converter"  # Replace with your repo's directory name
          MANIFEST_DIR="./manifest"  # Adjust if needed

          # Navigate to the home directory or your working directory
          cd ~  # Adjust this to your preferred directory if needed

          # Step 1: Check if the directory exists and delete it if it does
          if [ -d "$REPO_DIR" ]; then
              echo "Directory $REPO_DIR exists. Removing it..."
              rm -rf "$REPO_DIR"
          else
              echo "Directory $REPO_DIR does not exist. Proceeding to clone."
          fi

          # Step 2: Clone the repository
          echo "Cloning repository..."
          git clone "$REPO_URL"

          echo "Process completed successfully."
        EOF

    # Step 5: Deploy Backend to Minikube on EC2
    - name: Deploy Backend Microservices
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
          echo "Applying Kubernetes manifests..."
          cd RapidFort-Assignment/word-to-pdf-converter-backend
          for service in gateway docx-to-pdf-converter notification metadata download rabbit; do
            sudo kubectl apply -f $service/manifest
          done
        EOF
