name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io  # Use Docker Hub or change to AWS ECR if needed
      REPO: kingshukbansal/rapid-fort  # Replace with your Docker Hub username or ECR repo name
      KUBECONFIG: /home/runner/.kube/config

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub or AWS ECR
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push images for all services
    - name: Build and push Docker images
      run: |
        for service in rabbit gateway notification docxtopdfconverter metadata; do
          docker build -t $REGISTRY/$REPO/$service:latest -f $service/Dockerfile $service
          docker push $REGISTRY/$REPO/$service:latest
        done

    # Set up Minikube on the EC2 instance
    - name: Set up SSH to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Start Minikube if not running
          if ! minikube status; then
            minikube start --driver=none
          fi
          
          # Apply Kubernetes manifests
          kubectl apply -f /path/to/your/project/manifest
