name: Deploy Backend Microservices

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Add SSH Key for EC2 Access
      run: |
        echo "${{ secrets.SSH_KEY }}" > /tmp/id_rsa.pem
        chmod 600 /tmp/id_rsa.pem
        cat /tmp/id_rsa.pem



    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Build and Push Docker Images for Backend Microservices
    - name: Build and Push Backend Images
      run: |
        cd word-to-pdf-converter-backend
        for service in gateway docx-to-pdf-converter notification metadata download; do
          echo "Building and pushing $service..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rapidfort-$service:latest $service
          docker push ${{ secrets.DOCKER_USERNAME }}/rapidfort-$service:latest
        done

    # Step 4: Add SSH Key for EC2 Access (this should be before the deploy step)
    - name: Add SSH Key
      run: |
        echo "${{ secrets.SSH_KEY }}" | base64 --decode > /tmp/id_rsa
        chmod 600 /tmp/id_rsa


    # Step 5: Deploy Backend to Minikube on EC2
    - name: Deploy Backend Microservices
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << EOF
          echo "Applying Kubernetes manifests..."
          cd word-to-pdf-converter-backend
          for service in gateway docx-to-pdf-converter notification metadata download rabbit; do
            kubectl apply -f $service/manifest
          done
        EOF
